### PR TITLE
replace obsolete macros AC_HELP_STRING and AC_TRY_LINK

### PR DESCRIPTION
**Pull request by shuxiao9058**

### CODE REVIEW

**Comment by shuxiao9058** [comment]
@nicm could you help review and then merge this pr?

**Comment by nicm** [comment]
It looks good but can you remove the redundant extra [] in AS_HELP_STRING, AC_CONFIG_FILES and I think also around b64_ntop? Thanks.

**Comment by shuxiao9058** [comment]
done some minor change, but others i don't know what you mean?

**Comment by nicm** [comment]
Applied now with some minor tweaks, thanks!

**Comment by shuxiao9058** [comment]
Can you make a new tag `v2.2.1` ? I want to update the macports ports to latest version.

**Pull request closed without merging**
