### PR TITLE
Add "insecure" flag to pop3s and imaps

### PR DESCRIPTION
**Pull request by gmp216**
Update pop3s and imaps protocols to use secure TLS protocols by default, unless the "insecure" flag is specified in the account definition in fdm.conf. By default, SSLv2, SSLv3 and TLSv1.0 will be disabled by default.

### CODE REVIEW

**Comment by nicm** [comment]
-.Op Ic no-tls1
+.Op Ic tls1

This should be "insecure".

Otherwise looks good but can you please fix the indentation, wrap lines
at 80 columns and match the existing code style (for example, "if (" not
"if(").

**Comment by gmp216** [comment]
See latest commit for cleanups.

**Comment by nicm** [comment]
I have applied this, with some minor tweaks, I can't test it at the moment so hopefully it is right, please let me know if not.

**Comment by gmp216** [comment]
Haven't done any regression testing but it builds fine and runs on my end. Looks good so far.

**Comment by nicm** [comment]
-.Op Ic no-tls1
+.Op Ic tls1

This should be "insecure".

Otherwise looks good but can you please fix the indentation, wrap lines
at 80 columns and match the existing code style (for example, "if (" not
"if(").

**Pull request closed without merging**
