### PR TITLE
Compatibility fixes.

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by nicm** [comment]
a) Please define WAIT_ANY in fdm.h if it is not already there.

b) Did you write this code or where did it come from? It needs to go in compat/.

**Comment by neheb** [comment]
a) ok

b) I took the code from: https://github.com/novnc/websockify/pull/329/commits/3a03e3c59d48853562feff82f9c7461f5e00692e . Will move it to compat

**Comment by nicm** [comment]
I can't see any licensing information on this project, did you write it? I
suggest you take the b64 code from tmux instead because I know it has an
acceptable license.

**Comment by neheb** [comment]
It's LGPLv3. Will look at it and adjust in a few hours.

**Comment by nicm** [comment]
OK please don't use that code then, there are alternatives that are BSD
licensed.

**Comment by neheb** [comment]
I force pushed new commits with better descriptions. Hopefully this is OK.

**Comment by nicm** [comment]
Looks good but I think it also needs this bit at the end of Makefile.am:
~~~~
if NO_B64_NTOP
nodist_fdm_SOURCES += compat/base64.c
endif

**Comment by neheb** [comment]
Will do in an hour.

Btw, this all came about as the old sourceforge link for fdm died. I switched it to here but the code base seems to differ. The OpenWrt patches don't apply anomore as a result. Any insight into that?

More details: https://github.com/openwrt/packages/pull/5826

**Comment by nicm** [comment]
Applied now thanks.

**Pull request closed without merging**
